name: CMake

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # Google drive file id
  GDRIVE_FILE_ID: 1WxCknAfmcooVhKi3YYerqdxOd5_lwpQA

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache vcpkg-export.7z
        id: cache-vcpkg-export
        uses: actions/cache@v3
        with:
          path: vcpkg-export.7z
          key: vcpkg-export.7z

      - name: Download google drive file
        if: steps.cache-vcpkg-export.outputs.cache-hit != 'true'
        run: |
          echo "Install gdown"
          pip3 install gdown
          echo "Download vcpkg-export.7z"
          gdown ${{env.GDRIVE_FILE_ID}}

      - name: Extract vcpkg-export.7z
        run: 7z x vcpkg-export.7z -o${{github.workspace}}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DVCPKG_MANIFEST_MODE=OFF -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg-export/scripts/buildsystems/vcpkg.cmake

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # - name: Test
      # working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      # run: ctest -C ${{env.BUILD_TYPE}}

      - name: Mac deploy
        run: macdeployqt ${{github.workspace}}/build/CopyPlusPlus-QtWidget.app -dmg

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CopyPlusPlus
          path: ${{github.workspace}}/build/CopyPlusPlus-QtWidget.dmg

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: CopyPlusPlus
